# Generated by Django 4.0.6 on 2022-08-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
